In [1]:
from scipy.io import loadmat

In [3]:
import os
os.getcwd()

'D:\\downloads\\buf\\resources\\src'

In [4]:
train_mat = loadmat('../train/digitStruct.mat')

NotImplementedError: Please use HDF reader for matlab v7.3 files

https://stackoverflow.com/questions/17316880/reading-v-7-3-mat-file-in-python

In [6]:
import h5py
with h5py.File('../train/digitStruct.mat', 'r') as f:
    print(f.keys())

KeysView(<HDF5 file "digitStruct.mat" (mode r)>)


In [8]:
import numpy as np
arrays = {}
with h5py.File('../train/digitStruct.mat', 'r') as f:
    for k, v in f.items():
        arrays[k] = np.array(v)

In [9]:
for k in arrays:
    print(k)

#refs#
digitStruct


In [10]:
type(arrays[k])

numpy.ndarray

In [11]:
arrays[k].shape

(2,)

In [12]:
arrays[k][0]

'bbox'

In [13]:
arrays[k][1]

'name'

In [18]:
arrays['#refs#']

array(['#a', '#b', '#c', ..., 'zzx', 'zzy', 'zzz'], dtype='<U3')

In [20]:
arrays['digitStruct']

array(['bbox', 'name'], dtype='<U4')

In [ ]:
!pip install hdf5storage

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [ ]:
import hdf5storage
mat = hdf5storage.loadmat('../train/digitStruct.mat')

In [ ]:
type(mat)

In [1]:
import h5py
labels_file = '../train/digitStruct.mat'
f = h5py.File(labels_file)
ref = f.get('/digitStruct/name').value[0][0]  # <HDF5 object reference>
print(f[ref].value)

[[ 49]
 [ 46]
 [112]
 [110]
 [103]]


D:\application\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
ref = f.get('/digitStruct/name').value[1][0]  # <HDF5 object reference>
print(f[ref].value)

[[ 50]
 [ 46]
 [112]
 [110]
 [103]]


In [4]:
ref = f.get('/digitStruct/name').value[2][0]  # <HDF5 object reference>
print(f[ref].value)

[[ 51]
 [ 46]
 [112]
 [110]
 [103]]


In [1]:
from utils import *

D:\application\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
root_path = '../data/train/'
X,X_boxes,Y = load_data(root_path,True)

loading sample 0
loading sample 1
loading sample 2
loading sample 3
loading sample 4
loaded 5 samples
X: (5,)
X_boxes: (5, 2, 4)
Y: (5, 2)


In [5]:
X[0].shape

(350, 741, 3)

In [6]:
Y[0]

array([1, 9])

In [7]:
Y[1]

array([2, 3])

In [8]:
X_boxes[0][0]

array([246,  77,  81, 219])

png读进来是RGB彩色的，但是分类数字串并不需要颜色来辅助，可以转换为灰度图像。物体检测，画框框可能是需要颜色的。

In [2]:
root_path = '../data/train/'
X,X_boxes,Y = load_data(root_path,False)

loaded 33402 samples
X: (33402,)
X_boxes: (33402,)
Y: (33402,)


In [3]:
max_len = -1
for digits in Y:
    digit_num = len(digits)
    if digit_num > max_len:
        max_len = digit_num
print(max_len)

6


测试集和训练集里面只有一张图片是有6个数字的（这张图片出现在训练集里）