In [1]:
from keras.layers import Flatten, Dense, Dropout,Input
from keras.applications import resnet50
from keras.models import Model
from keras.layers.normalization import BatchNormalization
from keras import backend as K
import tensorflow as tf
import numpy as np
import pickle

Using TensorFlow backend.


In [2]:
with open('../data/train_rgb.pkl', 'rb') as f:
    X_train, Y_train = pickle.load(f)
with open('../data/test_rgb.pkl', 'rb') as f:
    X_test, Y_test = pickle.load(f)

In [3]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(5, 64, 64, 3)
(5, 5, 11)
(5, 64, 64, 3)
(5, 5, 11)


In [4]:
base_model = resnet50.ResNet50(include_top=False, weights='imagenet', input_tensor=Input(shape=(64,64,3)), pooling=True, classes=1000)
for layer in base_model.layers:
    layer.trainable=False
# input_layer = Input(shape=(None, None, 3))
x = Flatten()(base_model.output)
x = Dense(128,activation='relu')(x)
x = Dropout(0.2)(x)
x = BatchNormalization()(x)
pred1 = Dense(11,activation='softmax')(x)
pred2 = Dense(11,activation='softmax')(x)
pred3 = Dense(11,activation='softmax')(x)
pred4 = Dense(11,activation='softmax')(x)
pred5 = Dense(11,activation='softmax')(x)

# X = tf.placeholder(tf.float32, [None, 64, 64, 3])
# Y = tf.placeholder(tf.int32, [None, 5, 11])
# loss1 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 0, :], logits=pred1))
# loss2 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 1, :], logits=pred2))
# loss3 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 2, :], logits=pred3))
# loss4 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 3, :], logits=pred4))
# loss5 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 4, :], logits=pred5))
# loss = loss1 + loss2 + loss3 +loss4 + loss5

# multi_accuracy =
outputs =  [pred1,pred2,pred3,pred4,pred5]
model = Model(input=base_model.input,output = outputs)
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.6/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 64, 64, 3)    0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 70, 70, 3)    0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 32, 32, 64)   9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 32, 32, 64)   256         conv1[0][0]                      
__________________________________________________________________________________________________
activation

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:26: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=[<tf.Tenso...)`


In [5]:
print(Y_train)

[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]]


In [6]:
Y_train = list(Y_train)
Y_test = list(Y_test)

In [7]:
print(Y_train)

[array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32), array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32), array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32), array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [19]:
# 把Y_train转成np array的话,fit会报错
# print(Y_train.shape)
# print(Y_test.shape)
history = model.fit(x = X_train,y = Y_train,
                                 batch_size = 64,
                                 epochs= 5,
                                 verbose=1,
                                 shuffle = True,
                                 )
probs = model.predict(X_train)
loss_val = model.evaluate(X_train, Y_train, verbose=0)

Epoch 1/5
5/5 [==============================] - 0s 21ms/step - loss: 5.6816 - dense_2_loss: 0.8456 - dense_3_loss: 1.0062 - dense_4_loss: 1.2246 - dense_5_loss: 1.5906 - dense_6_loss: 1.0146 - dense_2_acc: 1.0000 - dense_3_acc: 0.6000 - dense_4_acc: 0.6000 - dense_5_acc: 0.4000 - dense_6_acc: 0.6000
Epoch 2/5
5/5 [==============================] - 0s 18ms/step - loss: 5.2931 - dense_2_loss: 0.8977 - dense_3_loss: 1.1128 - dense_4_loss: 1.0805 - dense_5_loss: 1.1798 - dense_6_loss: 1.0223 - dense_2_acc: 1.0000 - dense_3_acc: 0.6000 - dense_4_acc: 0.6000 - dense_5_acc: 0.8000 - dense_6_acc: 0.6000
Epoch 3/5
5/5 [==============================] - 0s 22ms/step - loss: 5.4240 - dense_2_loss: 0.8604 - dense_3_loss: 0.8566 - dense_4_loss: 1.5786 - dense_5_loss: 1.1186 - dense_6_loss: 1.0099 - dense_2_acc: 0.8000 - dense_3_acc: 1.0000 - dense_4_acc: 0.8000 - dense_5_acc: 0.8000 - dense_6_acc: 1.0000
Epoch 4/5
5/5 [==============================] - 0s 18ms/step - loss: 4.8726 - dense_2_loss: 0

In [20]:
print(np.sum(probs[0],axis = 1)) #第一个样本

[1.        0.9999999 1.        1.        1.       ]


In [21]:
print(np.array(probs).shape)

(5, 5, 11)


In [22]:
print(np.array(Y_train).shape)

(5, 5, 11)


In [28]:
print(np.argmax(Y_train[0],axis = 1))

[ 1  9 10 10 10]


In [29]:
print(np.argmax(probs[0],axis = 1))

[ 1  4 10 10 10]


In [30]:
np.equal(np.argmax(Y_train[0],axis = 1),np.argmax(probs[0],axis = 1).astype('uint8'))

array([ True, False,  True,  True,  True])

In [32]:
(np.argmax(Y_train[0],axis = 1) == np.argmax(probs[0],axis = 1)).all().astype('uint8')

0

In [ ]:
# 网上很多人single acc 这样算就到98%了；实际上这个算法虚高。很多论文也是这么算的。

In [33]:
single_true_cnt = 0
multi_true_cnt = 0
probs = np.array(probs)
Y_train = np.array(Y_train)
n_samples = Y_train.shape[0]
# print(np.equal(Y_train[i],probs[i]))
for i in range(n_samples):
    pred_digits = np.argmax(Y_train[i],axis = 1)
    true_digits = np.argmax(probs[i],axis = 1)
    single_true_cnt += np.sum(np.equal(pred_digits,true_digits).astype('uint8'))
    multi_true_cnt += np.equal(pred_digits,true_digits).all().astype('uint8') #all判断全部相等
print(single_true_cnt)
print(multi_true_cnt)

11.0
0


In [34]:
for i in range(n_samples):
    print('-----')
    print(np.argmax(Y_train[i],axis = 1))
    print(np.argmax(probs[i],axis = 1))

-----
[ 1  9 10 10 10]
[ 1  4 10 10 10]
-----
[ 2  3 10 10 10]
[ 2  2 10  5  2]
-----
[ 2  5 10 10 10]
[ 2 10 10  4  5]
-----
[ 9  3 10 10 10]
[ 4  1 10  0  4]
-----
[ 3  1 10 10 10]
[ 3  4 10  1  0]


In [4]:
def cal_acc(probs,Y):
    probs = np.array(probs)
    Y = np.array(Y)
    single_true_cnt = 0
    multi_true_cnt = 0
    n_samples = Y.shape[0]
    for i in range(n_samples):
        pred_digits = np.argmax(Y[i],axis = 1)
        true_digits = np.argmax(probs[i],axis = 1)
        single_true_cnt += np.sum(np.equal(pred_digits,true_digits).astype('uint8'))
        multi_true_cnt += np.equal(pred_digits,true_digits).all().astype('uint8') #all判断全部相等
    single_digit_acc = single_true_cnt / Y.shape[0] / Y.shape[1]
    seq_acc = multi_true_cnt / Y.shape[0]
    return single_digit_acc,seq_acc

In [41]:
trainpAcc,seqTrainAcc = cal_acc(probs,Y_train)
print('digit1', 'digit2','digit3','digit4','digit5')
print('Train loss:', scoreTr)
print(len(scoreTr)) #包含总loss 各loss 各acc
print(scoreTr[0])
print(sum(scoreTr[1:7]))
print('Train accuracy:', trainpAcc)
print('Train sequence accuracy:', seqTrainAcc)

digit1 digit2 digit3 digit4 digit5
Train loss: [25.270610809326172, 1.9176712036132812, 4.836152076721191, 5.952731609344482, 5.910942077636719, 6.653114318847656, 0.6000000238418579, 0.20000000298023224, 0.0, 0.20000000298023224, 0.20000000298023224]
11
25.270610809326172
25.870611310005188
Train accuracy: 0.44000000000000006
Train sequence accuracy: 0.0


https://stackoverflow.com/questions/37657260/how-to-implement-custom-metric-in-keras

In [5]:
from keras.callbacks import Callback
class Acc(Callback):
    def on_train_begin(self, logs={}):
        self._data = []

    def on_epoch_end(self, batch, logs={}):
        X_val, Y_val = self.validation_data[0], self.validation_data[1]
        probs = model.predict(X_val)
        single_acc,seq_acc = cal_acc(probs,Y_val)
        print('single digit acc:',single_acc)
        print('sequence acc:',seq_acc)
        self._data.append({
            'accs': (single_acc, seq_acc),
        })
        return
    def get_data(self):
        return self._data

In [6]:
base_model = resnet50.ResNet50(include_top=False, weights='imagenet', input_tensor=Input(shape=(64,64,3)), pooling=True, classes=1000)
for layer in base_model.layers:
    layer.trainable=False
# input_layer = Input(shape=(None, None, 3))
x = Flatten()(base_model.output)
x = Dense(128,activation='relu')(x)
x = Dropout(0.2)(x)
x = BatchNormalization()(x)
pred1 = Dense(11,activation='softmax')(x)
pred2 = Dense(11,activation='softmax')(x)
pred3 = Dense(11,activation='softmax')(x)
pred4 = Dense(11,activation='softmax')(x)
pred5 = Dense(11,activation='softmax')(x)

# X = tf.placeholder(tf.float32, [None, 64, 64, 3])
# Y = tf.placeholder(tf.int32, [None, 5, 11])
# loss1 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 0, :], logits=pred1))
# loss2 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 1, :], logits=pred2))
# loss3 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 2, :], logits=pred3))
# loss4 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 3, :], logits=pred4))
# loss5 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y[:, 4, :], logits=pred5))
# loss = loss1 + loss2 + loss3 +loss4 + loss5

# multi_accuracy =
outputs =  [pred1,pred2,pred3,pred4,pred5]
model = Model(input=base_model.input,output = outputs)

/usr/local/lib/python3.6/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:26: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=[<tf.Tenso...)`


In [7]:
Y_train = list(Y_train)
Y_test = list(Y_test)

In [9]:
acc = Acc()
# model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'],callbacks = [acc])
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(x = X_train,y = Y_train,
                                 batch_size = 64,
                                 epochs= 5,
                                 verbose=1,
                                 shuffle = True,
                                 )
probs = model.predict(X_train)

Epoch 1/5
5/5 [==============================] - 3s 653ms/step - loss: 15.9078 - dense_2_loss: 3.4026 - dense_3_loss: 2.9689 - dense_4_loss: 3.2151 - dense_5_loss: 3.3930 - dense_6_loss: 2.9282 - dense_2_acc: 0.0000e+00 - dense_3_acc: 0.0000e+00 - dense_4_acc: 0.2000 - dense_5_acc: 0.0000e+00 - dense_6_acc: 0.0000e+00
Epoch 2/5
5/5 [==============================] - 0s 22ms/step - loss: 10.6449 - dense_2_loss: 2.2080 - dense_3_loss: 1.8802 - dense_4_loss: 2.0465 - dense_5_loss: 2.1856 - dense_6_loss: 2.3247 - dense_2_acc: 0.0000e+00 - dense_3_acc: 0.2000 - dense_4_acc: 0.2000 - dense_5_acc: 0.4000 - dense_6_acc: 0.4000
Epoch 3/5
5/5 [==============================] - 0s 19ms/step - loss: 8.1331 - dense_2_loss: 1.7227 - dense_3_loss: 1.3234 - dense_4_loss: 1.8305 - dense_5_loss: 1.4645 - dense_6_loss: 1.7920 - dense_2_acc: 0.4000 - dense_3_acc: 0.6000 - dense_4_acc: 0.2000 - dense_5_acc: 0.6000 - dense_6_acc: 0.4000
Epoch 4/5
5/5 [==============================] - 0s 20ms/step - loss: 7

回调应该可以实现实时输出，seq_acc，但是还是比较麻烦的。